### ISSUE TITLE
Lexemes challenge: support for klingon letters

### ISSUE THREAD

**Issue by fuddl** [envlh/dicare-tools#12]
Currently [klingon letters in the lexermes challange](https://dicare.toolforge.org/lexemes/challenge.php?id=3#Q10134)  look like this:
![not working Klingon letters in lexemes challange](https://github.com/envlh/dicare-tools/assets/842548/841c9f6d-c3b5-4fb3-9107-ed0fe735d5d3)

With a [dedicated font](https://github.com/fuddl/pIqaDqoq) it could look like this:
![Klingon letters in lexemes challange](https://github.com/envlh/dicare-tools/assets/842548/7ff56480-976d-4863-85c4-f6284e4a104c)

You could simply define it as a fallback

```css
@font-face {
  font-family: 'DIn pIqaD';
  src: url(dist/DIn pIqaD.woff);
  unicode-range: U+F8D0-F8E9,U+F8F0-F8F9,U+F8FD-F8FF;
}

body, input, select {
    font-family: "Open Sans", 'DIn pIqaD', sans-serif;
    font-size: 14px;
    background: #FFF;
}
```

or scope it to a specific language:
```css
td:lang(tlh) {
   font-family: 'DIn pIqaD', monospace;
}

```
